package jp.co.hiropro.seminar_hall.util;

/**
 * Created by Hss on 8/19/2015.
 */
public class KeyParser {

    public enum KEY {
        STATUS("status"),
        RANKING("ranking"),
        TITLE("title"),
        CATEGORY("category"),
        DURATION("duration"),
        LEVEL("level"),
        IMAGE("image"),
        CREATED("created_at"),
        MODIFIED("modified"),
        POSITION("position"),
        ID("id"),
        PASSED("passed"),
        CTFC_DESCRIPTION("ctfc_description"),
        CERTIFICATE_NAME("certificate_name"),
        PARENT_ID("parent_id"),
        QUESTIONS("questions"),
        RESULT("result"),
        SUMMARY("summary"),
        LONG_DESCRIPTION("long_description"),
        THUMBNAIL_URL("thumbnail_url"),
        SMALL_THUMBNAIL_URL("small_thumbnail_url"),
        NAME("name"),
        MESSAGE("message"),
        VIDEOS("videos"),
        ACHIEVEMENT("achievement"),
        CERTIFICATE("certificates"),
        IS_NEW("is_new"),
        NEXT_PAGE("next_page"),
        THUMBNAIL("thumbnail"),
        DESCRIPTION("description"),
        IS_FREE("is_free"),
        IS_LOCK("is_lock"),
        LOCK("lock"),
        BOUGHT("bought"),
        VIEWED("viewed"),
        CAT_ID("cat_id"),
        CAT_TITLE("cat_title"),
        MOVIE_ID("mid"),
        DATE("date"),
        DATA("data"),
        USER_CODE("user_code"),
        NUMBER_FOOT("number"),
        USER_MEMBER_ID("user_member_id"),
        CONTACT_ID("contact_id"),
        NEWS("news"),
        EASY("easy"),
        MIDDLE("middle"),
        HIGH("high"),
        TOTAL("total"),
        QUESTION("question"),
        ALLOW_BUY("allow_buy"),
        CATEGORIES("categories"),
        YES("yes"),
        CERTIFICATE_ID("certificate_id"),
        NO("no"),
        SG1("sg1"),
        SG2("sg2"),
        SG3("sg3"),
        SG4("sg4"),
        COMMENTE("commentE"),
        COMMENTF("commentF"),
        COMMENTB("commentB"),
        COMMENTC("commentC"),
        NAME_LESSION_UNLOCK("name_lession_unlock"),
        SUGGEST("suggest"),
        COMMENT("comment"),
        TITLE_VIDEOS("title_videos"),
        ANDROID_CODE_BUY("android_buy_code"),
        MOVIE_URL_MB_SQ("movie_url_mb_sq"),
        KEY_NAME_RANK("achievement"),
        KEY_PRICE("price"),
        MOVIE_URL_MB_LQ("movie_url_mb_lq"),
        LINK("link"),
        HEIGHT("height"),
        URL("url"),
        LIST("list"),
        ANSWER("answer"),
        WEB_VIEW("web_view"),
        BANNER("banner"),
        UNREAD_REMAIN("unread_remain"),
        UNREAD("unread"),
        READ("read"),
        SEND_AT("send_at"),
        USER_CLIENT_ID("user_client_id"),
        CATE_TITLE("cate_title"),
        SUBCATE_TITLE("subcate_title"),
        TOP("top"),
        PAGE("page"),
        ROLE_USER("role_user"),
        PROFILE("profile"),
        VIDEO_INTRO("introduction_video"),
        FULL_NAME("fullname"),
        AVATAR("avatar"),
        S_YOUTUBE("social_youtube"),
        S_GOOGLE("social_google"),
        S_FACE("social_face"),
        S_TWITTER("social_twitter"),
        S_INSTAGRAM("social_instagram"),
        IS_NEW_REGISTER("isNewRegister"),
        LIST_CATEGORY("list_category"),
        FAV_ID("fav_id"),
        BODY("body"), BANNER_URL("banner_url");
        String name = "";


        KEY(String response_status) {
            name = response_status;
        }

        @Override
        public String toString() {
            return name;
        }
    }
}
